name = "beencode"
version = "1.0.0"

description = "ğŸ bencode in Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "giacomocavalieri", repo = "project" }

[dependencies]
gleam_stdlib = ">= 0.50.0 and < 2.0.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
simplifile = ">= 2.0.0 and < 3.0.0"
prng = ">= 4.0.1 and < 5.0.0"
gleeunit = ">= 1.2.0 and < 2.0.0"
bento = ">= 1.0.0 and < 2.0.0"
glychee = ">= 1.1.2 and < 2.0.0"
